apiVersion: v1
kind: Service
metadata:
  name: n8n-db-lb
  namespace: n8n
  annotations:
    external-dns.alpha.kubernetes.io/hostname: n8n-db.amdhql.org
  labels:
    cilium-lb-pool: pineapple-pool
spec:
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    cnpg.io/cluster: n8n-db-production-cnpg-v1
    role: primary
