apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-configmap
data:
  WEBHOOK_URL: "https://automation.amdhql.org"
  DB_TYPE: postgresdb
  DB_POSTGRESDB_HOST: "n8n-db.amdhql.org"
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_SCHEMA: public
