apiVersion: v1
kind: Service
metadata:
  name: firefly-iii-db-lb
  namespace: firefly-iii
  annotations:
    external-dns.alpha.kubernetes.io/hostname: firefly-iii-db.amdhql.org
  labels:
    cilium-lb-pool: pineapple-pool
spec:
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    cnpg.io/cluster: firefly-iii-db-production-cnpg-v1
    role: primary
