apiVersion: v1
kind: Service
metadata:
  name: n8n
  annotations:
    external-dns.alpha.kubernetes.io/hostname: n8n.amdhql.org
  labels:
    cilium-lb-pool: pineapple-pool
spec:
  ports:
    - port: 5678
  selector:
    app: n8n
  type: ClusterIP
