apiVersion: v1
kind: ConfigMap
metadata:
  name: spotdl-playlists
  namespace: navidrome
data:
  playlist.txt: |
    https://open.spotify.com/playlist/37i9dQZEVXbJlfUljuZExa
    https://open.spotify.com/playlist/37i9dQZF1DWWuGaVZsglfu

